sudo: required

env:
  - ARCH_TRAVIS_VERBOSE=1

arch:
  repos:
    - xyne-any=http://xyne.archlinux.ca/repos/xyne
    - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
    - procps-ng # required by screenfetch
    - screenfetch
    # aur
    - archey3-git
    # papyros
    - papyros-shell
  script:
    - "sudo archey3"
    - "sudo screenfetch"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
