sudo: required

env:
  - ARCH_TRAVIS_VERBOSE=1

arch:
  aur:
    - archey3-git
  script:
    - "sudo archey3"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
